site_name: igrek51
repo_name: igrek51
repo_url: https://github.com/igrek51
site_author: igrek51
docs_dir: docs
edit_uri: ''
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: material/axis-y-arrow
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.expand
    - content.code.copy
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.blocks.caption
plugins: []
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/igrek51
      name: igrek51 on GitHub

nav:
  - Projects Portfolio: index.md
  - Cheatsheets:
    - ADB: cheatsheet/adb.md
    - Docker: cheatsheet/docker.md
    - Git: cheatsheet/git.md
    - Linux: cheatsheet/linux.md
    - Python: cheatsheet/python.md
    - Video: cheatsheet/video.md
    - Vim: cheatsheet/vim.md
  - Miscellaneous:
    - Day of the week: misc/a-day-in-the-life.md
    - Baby clothes taxonomy: misc/baby-clothes-taxonomy.md
    - Music Theory: misc/music-theory.md
    - Rubik's Cube: misc/rubik-cube.md
  - Journal:
    - Cloudflared Tunnel on Termux: journal/termux-tunnel.md
    - Async Python Pitfalls: journal/async-python.md
  - Internet status: status.md
